name: sockbot

services:
  bot:
    build: .
    container_name: sockbot
    restart: unless-stopped
    command: node src/index.js
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}dow
      - GUILD_ID=${GUILD_ID}
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
